print ("hello")
print('Hello world')
print('Benim yazdigim ilk kod')
print('Hello World!')
print('ben bunu yazmak istiyorum')
print('Hello World!')
print("Hello World!")
print('Hello World!')
print("Clarusway School!")
print("I'm happy to learn!")
print("Cift tirnak yazdim")
print('''uc tirnak ile yazdim''')
print("bir cumle")
print("I'm great")
print ('"hi" he said')
print('"hi" he said')
print('''Don't do it" said the manager''')